### ISSUE TITLE
adding names to images

### ISSUE THREAD

**Issue by eroux** [OpenPecha/prodigy-tools#13]
In the current prodigy interface, the "history" on the left looks like this:

![Capture d’écran de 2023-01-25 12-41-26](https://user-images.githubusercontent.com/60868/214554785-877aa1a0-6838-4b00-8900-fa904c5acb0d.png)

the `...` are not very helpful and I suspect there is a way to display the image file name there instead, perhaps through the `id` or `name` key in the stream returned by the recipes

**Comment by kaldan007** [comment]
@ta4tsering can u look a way to it.

**Comment by ta4tsering** [comment]
yes sure, I will look into it tomorrow.

**Comment by ta4tsering** [comment]
issue resolved, image_filename is displayed in the history
![Screenshot 2023-01-27 at 2 02 28 PM](https://user-images.githubusercontent.com/43548581/215042478-4428a275-4f27-4f96-8264-7dddd39a2c40.png)

**Comment by eroux** [comment]
thanks! @ta4tsering can you reference the issue in your commits? for instance in the commit where you fix this issue please have the message be "fix #13: ..."

**Comment by ta4tsering** [comment]
okay sure, I will commit and then push the changes with issue reference in the commit

**Comment by eroux** [comment]
looks good, thanks!
