### ISSUE TITLE
annotations cannot be saved red box

### ISSUE THREAD

**Issue by eroux** [OpenPecha/prodigy-tools#3]
This appears after some annotations:

<img width="351" alt="redbox" src="https://user-images.githubusercontent.com/60868/211022600-cddd6484-adc3-441b-b6c6-101e7bf94b2c.png">

also `/usr/local/prodigy/` does not contain the sqlite database that is configured in https://github.com/OpenPecha/prodigy-tools/blob/8b881f0f8d6c51352eece0af7687b8066df0e90f/configuration/bdrc_crop_images.json#L13 , perhaps these two are related

**Comment by ta4tsering** [comment]
so earlier there wasn't sqlite3 installed, so I installed it using `sudo apt-get install sqlite3` and now when I restarted the server and checked the log using `journalctl` it shows that sqlite is initialized as below
Jan 16 10:34:59 ip-172-31-85-61 prodigy_img[428895]: 10:34:59: DB: Initializing database SQLite
Jan 16 10:34:59 ip-172-31-85-61 prodigy_img[428895]: 10:34:59: DB: Connecting to database SQLite
Jan 16 10:34:59 ip-172-31-85-61 prodigy_img[428895]: 10:34:59: DB: Creating dataset '2023-01-16_10-34-59'
Jan 16 10:34:59 ip-172-31-85-61 prodigy_img[428895]: {'created': datetime.datetime(2022, 12, 23, 9, 5, 26)}

and I tried to annotated two pages and then clicked on the save button, it is saved as in the below image
![Screenshot 2023-01-16 at 4 39 06 PM](https://user-images.githubusercontent.com/43548581/212664900-211ac824-1dd9-428c-b9c0-5ee48999abd2.png)


but when I went to check inside the `/usr/local/prodigy` on the server for the `bdrc_crop_images.sqlite` as the path given in the configuration json file, the `bdrc_crop_images.sqlite` is not found there.

**Comment by eroux** [comment]
thanks, that's good progress! 

That's a bit strange... I wonder where Prodigy created the sqlite file...

**Comment by ta4tsering** [comment]
I will do more search or investigations, it should be somewhere on the server I think.

**Comment by eroux** [comment]
it seems that this is fixed, closing
