### ISSUE TITLE
Sampling Images for layout annotation

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/prodigy-tools#8]
- Top 5 and middle/bottom 5 images from every imagegroup.
- top offset: 5

**Comment by kaldan007** [comment]
top offset can be look at the property volumePagesTbrcIntro in the database, for instance in http://purl.bdrc.io/resource/I0886.ttl
for the bottom we don't have any other option then using list spliting. 
To get image list we can either look on S3 or through https://iiifpres.bdrc.io/il/v:bdr:{img_grp_id}

**Comment by kaldan007** [comment]
I think its better to go with 10 from top and 10 from bottom as we can ignore blank image using the ignore button.

**Comment by ta4tsering** [comment]
okay will look into it

**Comment by ta4tsering** [comment]
the link below is the script that takes a work_id, gives back a dict with imagegroup as key and s3_key of the top 10 and bottom 10 images from that imagegroup, excluding the tbrc intro images from the top.
[image sampling for layout analysis ](https://github.com/OpenPecha/prodigy-tools/blob/main/sampling_images_for_layout_analysis.py)
