### ISSUE TITLE
Custom Interface: add radio options for script classification

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/prodigy-tools#9]
Script detection (uchan, ume, etc)

**Comment by eroux** [comment]
@10zinten Prodigy can only work on a predefined list. What initial list of scripts are you thinking of?

**Comment by ta4tsering** [comment]
Created the recipe for script-detection and this what it shows right now. Comment for changes or suggestions
![Screenshot 2023-01-20 at 4 23 43 PM](https://user-images.githubusercontent.com/43548581/213678493-1c7047f7-6939-49f1-9d97-76b7dd041c67.png)
